
export default function PublicationsPage() {
    const papers = [
        {
            num: '01',
            year: '2022',
            title: 'Biosynthesis of tasikamides via pathway coupling and diazonium-mediated hydrazone formation',
            journal: 'Journal of the American Chemical Society',
            journalAbbr: 'J. Am. Chem. Soc.',
            authors: 'Ma, G.L., Candra, H., Pang, L.M., Xiong, J., Ding, Y., Tran, H.T., Low, Z.J., Ye, H., Liu, M., Zheng, J., Fang, M., Cao, B., and Liang, Z.-X.',
            abstract: 'Naturally occurring hydrazones are rare despite their universal usage in organic synthesis. This study details the discovery of tasikamides A–C, microbial metabolites with a unique cyclic pentapeptide scaffold and a hydrazone group. The biosynthesis involves the coupling of two discrete gene clusters—an NRPS pathway for the cyclic peptide and an AHA-synthesizing pathway—via a novel enzyme catalyzing an unprecedented in vivo Japp–Klingemann reaction.',
            doi: 'https://doi.org/10.1021/jacs.1c10369',
        },
        {
            num: '02',
            year: '2021',
            title: 'Pathway retrofitting yields insights into the biosynthesis of anthraquinone-fused enediynes',
            journal: 'Journal of the American Chemical Society',
            journalAbbr: 'J. Am. Chem. Soc.',
            authors: 'Ma, G.-L., Tran, H.T., Low, Z.J., Candra, H., Pang, L.M., Chang, Q.W., Fan, M.L., and Liang, Z.-X.',
            abstract: 'Anthraquinone-fused enediynes (AQEs) possess unique structures and potent anticancer properties, yet their biosynthesis has remained elusive. This study elucidates the biosynthesis of the AQE carbon skeleton by retrofitting the "degenerative" sungeidine pathway with genes from the dynemicin pathway, revealing a surprising enzymatic cascade involving an FAD-dependent monooxygenase.',
            doi: 'https://doi.org/10.1021/jacs.1c03911',
        },
        {
            num: '03',
            year: '2020',
            title: 'Sungeidines from a non-canonical enediyne biosynthetic pathway',
            journal: 'Journal of the American Chemical Society',
            journalAbbr: 'J. Am. Chem. Soc.',
            authors: 'Low, Z.J., Ma, G.-L., Tran, H.T., Zou, Y., Juan, X., Pang, L., Nuryyeva, S., Hong, Y., Hu, J., Houk, K.N., and Liang, Z.-X.',
            abstract: 'Sungeidines represent a novel class of microbial secondary metabolites discovered through genome-guided mining. While evolutionarily related to dynemicin-type enediynes, sungeidines are generated by a highly distinct biosynthetic gene cluster lacking canonical epoxidase genes, highlighting the remarkable evolutionary plasticity of enediyne biosynthetic pathways.',
            doi: 'https://doi.org/10.1021/jacs.9b10086',
        },
        {
            num: '04',
            year: '2016',
            title: 'A cyclic di-GMP-binding adaptor protein interacts with a chemotaxis methyltransferase to control flagellar motor switching',
            journal: 'Science Signaling',
            journalAbbr: 'Sci. Signal.',
            authors: 'Xu, L.H., Xing, L.Y., Zeng, Y., Yam, J.K.H., Ding, Y., Venkataramani, P., Cheang, Q.W., Yang, X., Tang, X., Zhang, L.-H., Chiam, K.-H., Yang, L., and Liang, Z.-X.',
            abstract: 'Cyclic di-GMP is a central second messenger regulating diverse processes in pathogenic bacteria, including motility and biofilm formation. This research identifies a novel c-di-GMP-binding adaptor protein that directly interacts with a chemotaxis methyltransferase, revealing a complex spatiotemporal signaling network that allows bacteria to dynamically adapt to host environments.',
            doi: 'https://doi.org/10.1126/scisignal.aaf7584',
        },
        {
            num: '05',
            year: '2013',
            title: 'Visualizing the perturbation of cellular cyclic di-GMP levels in bacterial cells',
            journal: 'Journal of the American Chemical Society',
            journalAbbr: 'J. Am. Chem. Soc.',
            authors: 'Ho, C.L., Chong, K.S.J., Oppong, J.A., Chuah, M.L.C., Tan, S.M., and Liang, Z.-X.',
            abstract: 'Understanding cyclic dinucleotide signaling requires precise visualization of its spatiotemporal dynamics within live cells. This study presents a novel method for visualizing the perturbation of cellular cyclic di-GMP levels in bacterial cells, providing critical insights into how bacteria regulate infection, virulence, and antibiotic resistance through synthase–phosphodiesterase circuits.',
            doi: 'https://doi.org/10.1021/ja310497x',
        },
    ]

    const grouped = papers.reduce<Record<string, typeof papers>>((acc, p) => {
        if (!acc[p.year]) acc[p.year] = [];
        acc[p.year].push(p);
        return acc;
    }, {});
    const years = Object.keys(grouped).sort((a, b) => Number(b) - Number(a));

    function highlightPI(authors: string) {
        const PI = 'Liang, Z.-X.';
        if (!authors.includes(PI)) return <>{authors}</>;
        const parts = authors.split(PI);
        return (
            <>
                {parts[0]}
                <span className="text-cyan-600 font-semibold">{PI}</span>
                {parts[1]}
            </>
        );
    }

    return (
        <main className="min-h-screen bg-white">
            <div className="bg-navy-950 text-white py-24 md:py-32 mb-16 relative overflow-hidden">
                <div className="absolute inset-0 z-0 bg-gradient-to-br from-navy-900 via-navy-950 to-[#000d1f]"></div>
                <div className="container mx-auto px-6 max-w-5xl relative z-10">
                    <div className="max-w-3xl">
                        <h1 className="text-5xl md:text-6xl font-extrabold tracking-tight mb-6 text-white">Publications</h1>
                        <p className="text-xl md:text-2xl text-gray-100 leading-relaxed font-light">
                            Selected recent publications from our laboratory.
                        </p>
                    </div>
                </div>
            </div>

            <div className="container mx-auto px-6 max-w-4xl pb-32">
                {years.map((year) => (
                    <div key={year} className="mb-16">
                        {/* Year divider */}
                        <div className="flex items-baseline gap-4 mb-10 border-b border-gray-100 pb-4">
                            <h2 className="text-5xl font-extrabold text-navy-900 tracking-tight">{year}</h2>
                            <div className="h-px flex-1 bg-gray-100"></div>
                        </div>

                        <div className="space-y-10">
                            {grouped[year].map((p) => (
                                <div
                                    key={p.num}
                                    className="group pl-5 border-l-2 border-gray-200 hover:border-cyan-500 transition-colors duration-300"
                                >
                                    {/* Citation line */}
                                    <p className="text-sm text-gray-500 mb-2 leading-relaxed">
                                        {highlightPI(p.authors)}{' '}
                                        <em>{p.journalAbbr}</em>{' '}
                                        <span className="text-gray-400">({p.year}).</span>
                                    </p>

                                    {/* Title */}
                                    <a
                                        href={p.doi}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="block text-base font-semibold text-navy-900 leading-snug group-hover:text-cyan-700 transition-colors mb-3"
                                    >
                                        {p.title}
                                    </a>

                                    {/* Abstract */}
                                    <p className="text-sm text-gray-500 leading-relaxed max-w-3xl mb-4">
                                        {p.abstract}
                                    </p>

                                    <a
                                        href={p.doi}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="inline-flex items-center gap-1 text-xs font-bold tracking-widest text-cyan-600 hover:text-cyan-800 transition-colors uppercase"
                                    >
                                        DOI ↗
                                    </a>
                                </div>
                            ))}
                        </div>
                    </div>
                ))}

                <div className="mt-4 pt-8 border-t border-gray-200">
                    <a
                        href="https://scholar.google.com/citations?user=F-DuOAkAAAAJ&hl=en"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="btn-primary"
                    >
                        View Full List on Google Scholar &rarr;
                    </a>
                </div>
            </div>
        </main>
    )
}
