
export default function PublicationsPage() {
    const papers = [
        {
            num: '01',
            year: '2022',
            title: 'Biosynthesis of tasikamides via pathway coupling and diazonium-mediated hydrazone formation',
            journal: 'Journal of the American Chemical Society',
            authors: 'Ma, G.L., Candra, H., Pang, L.M., Xiong, J., Ding, Y., Tran, H.T., Low, Z.J., Ye, H., Liu, M., Zheng, J., Fang, M., Cao, B., and Liang, Z.-X.',
            abstract: 'Naturally occurring hydrazones are rare despite their universal usage in organic synthesis. This study details the discovery of tasikamides A–C, microbial metabolites with a unique cyclic pentapeptide scaffold and a hydrazone group. The biosynthesis involves the coupling of two discrete gene clusters—an NRPS pathway for the cyclic peptide and an AHA-synthesizing pathway—via a novel enzyme catalyzing an unprecedented in vivo Japp–Klingemann reaction.',
            doi: 'https://doi.org/10.1021/jacs.1c10369',
        },
        {
            num: '02',
            year: '2021',
            title: 'Pathway retrofitting yields insights into the biosynthesis of anthraquinone-fused enediynes',
            journal: 'Journal of the American Chemical Society',
            authors: 'Ma, G.-L., Tran, H.T., Low, Z.J., Candra, H., Pang, L.M., Chang, Q.W., Fan, M.L., and Liang, Z.-X.',
            abstract: 'Anthraquinone-fused enediynes (AQEs) possess unique structures and potent anticancer properties, yet their biosynthesis has remained elusive. This study elucidates the biosynthesis of the AQE carbon skeleton by retrofitting the "degenerative" sungeidine pathway with genes from the dynemicin pathway, revealing a surprising enzymatic cascade involving an FAD-dependent monooxygenase.',
            doi: 'https://doi.org/10.1021/jacs.1c03911',
        },
        {
            num: '03',
            year: '2020',
            title: 'Sungeidines from a non-canonical enediyne biosynthetic pathway',
            journal: 'Journal of the American Chemical Society',
            authors: 'Low, Z.J., Ma, G.-L., Tran, H.T., Zou, Y., Juan, X., Pang, L., Nuryyeva, S., Hong, Y., Hu, J., Houk, K.N., and Liang, Z.-X.',
            abstract: 'Sungeidines represent a novel class of microbial secondary metabolites discovered through genome-guided mining. While evolutionarily related to dynemicin-type enediynes, sungeidines are generated by a highly distinct biosynthetic gene cluster lacking canonical epoxidase genes, highlighting the remarkable evolutionary plasticity of enediyne biosynthetic pathways.',
            doi: 'https://doi.org/10.1021/jacs.9b10086',
        },
        {
            num: '04',
            year: '2016',
            title: 'A cyclic di-GMP-binding adaptor protein interacts with a chemotaxis methyltransferase to control flagellar motor switching',
            journal: 'Science Signaling',
            authors: 'Xu, L.H., Xing, L.Y., Zeng, Y., Yam, J.K.H., Ding, Y., Venkataramani, P., Cheang, Q.W., Yang, X., Tang, X., Zhang, L.-H., Chiam, K.-H., Yang, L., and Liang, Z.-X.',
            abstract: 'Cyclic di-GMP is a central second messenger regulating diverse processes in pathogenic bacteria, including motility and biofilm formation. This research identifies a novel c-di-GMP-binding adaptor protein that directly interacts with a chemotaxis methyltransferase, revealing a complex spatiotemporal signaling network that allows bacteria to dynamically adapt to host environments.',
            doi: 'https://doi.org/10.1126/scisignal.aaf7584',
        },
        {
            num: '05',
            year: '2013',
            title: 'Visualizing the perturbation of cellular cyclic di-GMP levels in bacterial cells',
            journal: 'Journal of the American Chemical Society',
            authors: 'Ho, C.L., Chong, K.S.J., Oppong, J.A., Chuah, M.L.C., Tan, S.M., and Liang, Z.-X.',
            abstract: 'Understanding cyclic dinucleotide signaling requires precise visualization of its spatiotemporal dynamics within live cells. This study presents a novel method for visualizing the perturbation of cellular cyclic di-GMP levels in bacterial cells, providing critical insights into how bacteria regulate infection, virulence, and antibiotic resistance through synthase–phosphodiesterase circuits.',
            doi: 'https://doi.org/10.1021/ja310497x',
        },
    ]

    return (
        <main className="min-h-screen bg-white">
            <div className="bg-navy-950 text-white py-24 md:py-32 mb-16 relative overflow-hidden">
                <div className="absolute inset-0 z-0 bg-gradient-to-br from-navy-900 via-navy-950 to-[#000d1f]"></div>
                <div className="absolute inset-0 z-0 bg-gradient-to-t from-white via-transparent to-transparent opacity-60"></div>
                <div className="container mx-auto px-6 max-w-5xl relative z-10">
                    <div className="max-w-3xl">
                        <h1 className="text-5xl md:text-6xl font-extrabold tracking-tight mb-6">Publications</h1>
                        <p className="text-xl md:text-2xl text-gray-200 leading-relaxed font-light">
                            Selected recent publications from our laboratory.
                        </p>
                    </div>
                </div>
            </div>

            <div className="container mx-auto px-6 max-w-5xl pb-32">
                <div className="space-y-0 divide-y divide-gray-100">
                    {papers.map((p) => (
                        <div key={p.num} className="py-10 group">
                            <div className="flex gap-6 items-baseline mb-3">
                                <span className="text-xs font-bold tracking-widest text-gray-300 uppercase shrink-0 w-6">{p.num}</span>
                                <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
                                    <span className="text-xs font-semibold tracking-wide text-white bg-navy-900 px-2.5 py-1 rounded">{p.year}</span>
                                    <span className="text-sm text-gray-500 italic">{p.journal}</span>
                                </div>
                            </div>
                            <div className="pl-12">
                                <h3 className="text-lg font-bold text-navy-900 mb-2 leading-snug group-hover:text-cyan-700 transition-colors">
                                    {p.title}
                                </h3>
                                <p className="text-sm text-gray-500 mb-3">{p.authors}</p>
                                <p className="text-sm text-gray-600 leading-relaxed mb-4 max-w-3xl">{p.abstract}</p>
                                <a
                                    href={p.doi}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="inline-flex items-center gap-1 text-sm font-medium text-cyan-600 hover:text-cyan-800 transition-colors"
                                >
                                    DOI ↗
                                </a>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="mt-12 pt-8 border-t border-gray-200">
                    <a
                        href="https://scholar.google.com/citations?user=F-DuOAkAAAAJ&hl=en"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="btn-primary"
                    >
                        View Full List on Google Scholar &rarr;
                    </a>
                </div>
            </div>
        </main>
    )
}
